### ISSUE TITLE
Import errors and Modules missing

### ISSUE THREAD

**Issue by jaimecorton** [capjamesg/sam-gpt4v#1]
Hello,

I've been trying to replicate the environment and I noticed that a pip install openai, roboflow is missing in order to have the code imports properly working (It seems to be ommited in the requirements.txt). Moreover, autodistill renamed one of the models that the script (samgpt.py) imports, so that, what was called CustomDetectionModel is now called ComposedDetectionModel as you can check in here -> [autodistill/core/composed_detection_model.py](https://github.com/autodistill/autodistill/blob/main/autodistill/core/composed_detection_model.py)

I don't know the reason of this changes in Autodistill and it seems that @capjamesg (creator of the sam-gpt4v repo) was the one making those changes recently according to the logs. Clarification on this would be more than welcomed. I suppose that just by changing the naming of the imports will be enough to make it work.

the change will be needed here:
`from autodistill.core.composed_detection_model import ComposedDetectionModel`

and here:
```
SAMGPT = ComposedDetectionModel(
    detection_model=GroundedSAM(
        CaptionOntology({"car": "car"})
    ),
    classification_model=GPT4V(
        CaptionOntology({k: k for k in classes})
    )
)
```

Thanks in advance!

**Comment by capjamesg** [comment]
Hello @jaimecorton! I had some local `autodistill` changes from a PR branch that were not available via PyPi while I was working on this project. I should have included instructions to pull from the branch and install from source while the module was uploaded. I have updated the project to use the new API name. The new `autodistill` release should also fix the `roboflow` import issue. Run `pip install --upgrade autodistill` to get the latest version.

**Comment by jaimecorton** [comment]
Hello again and thanks for the answer!

It seems to be solved then. Have a nice week!

I will close the issue.
